### ISSUE TITLE
Support LLVM 13

### ISSUE THREAD

**Issue by kmlebedev** [tinygo-org/go-llvm#60]
Hello, is it possible to support LLVM version 13.0.0?
for copying tinygo this is critically important to support go on e2k platforms (Elbrus)
I plan to insert go-llvm into the assembly pipeline with llcrt https://gitflic.ru/project/e2khome/lccrt

**Comment by aykevl** [comment]
TinyGo has dropped support for LLVM 13 a while ago, and is very unlikely to bring back this support. This is for many reasons, but most importantly because we now use opaque pointers instead of typed pointers and the oldest LLVM version supporting opaque pointers is LLVM 15.

Adding back support for LLVM 13 to go-llvm is fairly trivial, but if your goal is TinyGo support, that's not something we're going to do. Sorry about that.
